In [2]:
import numpy as np 

In [3]:
arr=np.array([10,20,30,40,50,60])
arr1=arr.reshape(2,3)
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
arr1.flatten()

array([10, 20, 30, 40, 50, 60])

In [4]:
a=np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
b=np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
c=np.arange(2,20,2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
d=np.linspace(2,20,5)
d

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [3]:
d=np.arange(1,12,2)
d

array([ 1,  3,  5,  7,  9, 11])